# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e4afc38e34cb05259d87186d2e03fc474f3cbb5596eb56929d4adcc29b007b560e2f5eed4a1e0f5d2e55bf5026a6721a41173877c9b1bb8a407037e57f141b5a

test:
  secret_key_base: 956891e85975f331c22629b6f198f380653c1f2afdb4a49a88488634ca02afc6ce7037d3a8572f711a92bd9696f52a8c5c76d39448cba14db95771ba2e568b7d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
